### ISSUE TITLE
packageとしてimport(あるいはgithub上でrelease)出来るような感じにしてみてほしい

### ISSUE THREAD

**Issue by nyangame** [VGA-GLAB/G-Lab-Library#2]
ここ参考にして  
https://zenn.dev/kameffee/articles/c49499f82ce81c

OpenUPMも対応するといいかも  
https://qiita.com/makihiro_dev/items/f2388081b828228ff54f

**Comment by HarumiMaruoka** [comment]
諸々対応しました！

**Comment by nyangame** [comment]
👍
